name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: When I try to use mock_http_request with form data...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Import mock_http_request
        2. Create request with form data
        3. Call get_form()
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: The form data should be parsed correctly...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Instead, I got a KeyError...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Minimal code sample that reproduces the issue
      render: python
      placeholder: |
        from azure_functions_test import mock_http_request

        req = mock_http_request(
            method="POST",
            body="name=Alice",
            headers={"Content-Type": "application/x-www-form-urlencoded"}
        )

        form = req.form  # Error occurs here
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your environment details
      value: |
        - azure-functions-test version:
        - azure-functions version:
        - Python version:
        - OS:
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional context, screenshots, or logs
      placeholder: Error traceback, screenshots, etc.
